### ISSUE TITLE
azure login mode

### ISSUE THREAD

**Issue by christopher-hesse** [christopher-hesse/blobfile#100]
It looks like there's no reliable way to detect if we can access a storage account, so we probably need `AZURE_STORAGE_AUTH_MODE` support in order to use key mode by default but allow users to select login mode.

The current check `_azure_can_access_account` returns true even if we can't read any of the containers because the permissions are wrong.

**Comment by christopherhesse** [comment]
Could default to login, and try to list blobs in the first container to see if we have blob access
