### ISSUE TITLE
Chunking for Azure

### ISSUE THREAD

**Issue by jacobhilton** [christopher-hesse/blobfile#116]
Currently, the following code seems to trigger many Azure API requests (one per line?):

```
with bf.BlobFile(AZURE_PATH) as f:
    for line in f:
        pass
```

Or at least it seems to easily trigger some kind throttling, perhaps the [20,000 requests per second](https://docs.microsoft.com/en-us/azure/azure-resource-manager/management/azure-subscription-service-limits#storage-limits) Azure API limit.

If possible, it might be good to chunk calls by default, e.g. to never read less than some default chunk size, and to keep hold of any extra data.

**Comment by hauntsaninja** [comment]
Defaults aside, you can pass in buffer_size to BlobFile, or use streaming=False

**Comment by christopher-hesse** [comment]
I think I noticed some odd behavior with this.  If you do `bf.BlobFile(AZURE_PATH, "rb")`, does that do fewer requests?  I suspect there is some weird behavior with `io.BufferedReader` when `io.TextIOWrapper` is used, but haven't investigated.

**Comment by hauntsaninja** [comment]
There might also be some XY problem going on. This thread has more context: https://openai.slack.com/archives/C1UA8LT0T/p1598543157272500

**Comment by jacobhilton** [comment]
Yes it seems like it's not an Azure rate limit after all, but some other source of throttling (though it only seems to occur when reading line-by-line). Using `bf.BlobFile(AZURE_PATH, "rb")` doesn't seem to help. Feel free to close if this isn't the best place to discuss this.

**Comment by jacobhilton** [comment]
Closed as I was unable to reproduce this on an Azure-hosted machine.
