### ISSUE TITLE
Not possible to read from public Azure blobs without authentication

### ISSUE THREAD

**Issue by daniel-ziegler** [christopher-hesse/blobfile#118]
This came up at https://github.com/openai/summarize-from-feedback/issues/2.

Steps to reproduce:
1. Find a machine that isn't authenticated in Azure
2. Verify that a browser can access `https://openaipublic.blob.core.windows.net/summarize-from-feedback/encodings/reversible_50000/encoder.json` -- it is indeed public
3. Run `bf.BlobFile("https://openaipublic.blob.core.windows.net/summarize-from-feedback/encodings/reversible_50000/encoder.json", "r")`

What happens:
`blobfile` prompts you to log in to an Azure account. If you log in to an Azure account that lacks write access to `openaipublic`, then I believe it still fails with `blobfile.common.Error: Found storage account key, but it was unable to access storage account: 'openaipublic'`.

What should happen:
`blobfile` only asks for authentication if needed.

**Comment by christopher-hesse** [comment]
I think blobfile should try anonymous access before returning an error.  However, blobfile checks permissions at the account level and public access is done at the container or blob level, so I may need to change a bit about how it works.

**Comment by christopher-hesse** [comment]
Would it be fine if this only supports public containers @daniel-ziegler?

**Comment by christopher-hesse** [comment]
Here's the table of settings: https://docs.microsoft.com/en-us/azure/storage/blobs/anonymous-read-access-configure?tabs=portal#about-anonymous-public-read-access

**Comment by daniel-ziegler** [comment]
> Would it be fine if this only supports public containers @daniel-ziegler?

That would definitely suffice for my use case!

**Comment by christopher-hesse** [comment]
I switched access tokens to be per (account, container) instead of per account, and added an anonymous account that will be tried last when accessing an (account, container) pair.  I believe `blobfile` will still fail if the user has no azure credentials available though, do you need that for your use case?

**Comment by christopher-hesse** [comment]
I added the support for no azure credentials here: https://github.com/christopher-hesse/blobfile/commit/395e362baa54d7592280bd57f5e904248c393458

Let me know if the master branch fixes your issue, @daniel-ziegler

**Comment by daniel-ziegler** [comment]
Seems to work, thanks!

**Comment by christopher-hesse** [comment]
Should be fixed in version 0.17.2, thanks for filing this issue!
