### ISSUE TITLE
bf.copy doesn't work across azure storage accounts

### ISSUE THREAD

**Issue by hauntsaninja** [christopher-hesse/blobfile#119]
It seems to work if you use an SAS signed URL for x-ms-copy-source, so shouldn't be too hard to fix (modulo source with anonymous access).

> However, if the source is a blob in another account, the source blob must either be public or must be authorized via a shared access signature. If the source blob is public, no authorization is required to perform the copy operation.

https://docs.microsoft.com/en-us/rest/api/storageservices/copy-blob

**Comment by christopher-hesse** [comment]
Good catch!  Thanks for reporting this.

**Comment by christopher-hesse** [comment]
Should be fixed on master, let me know if that doesn't work for you and/or if you want me to publish a new version with this fix.

**Comment by hauntsaninja** [comment]
Thanks, master works for me! You could also extend the check for `if sas_token is None or src_account == dst_account:` to potentially save a request

**Comment by christopher-hesse** [comment]
I guess that's only 1 request, not 1 request per copy due to caching, but seems like a good suggestion.

**Comment by christopher-hesse** [comment]
Fixed in https://github.com/christopher-hesse/blobfile/commit/01ba28b0aa18ee803d6203fbc49118d8027e17cb
