### ISSUE TITLE
Stub files should use "as"

### ISSUE THREAD

**Issue by christopherhesse** [christopher-hesse/blobfile#142]
https://www.python.org/dev/peps/pep-0484/#stub-files
https://github.com/microsoft/pyright/issues/1128
https://youtrack.jetbrains.com/issue/PY-43203?clearDraft=true&description=%0A%0APC-201.7846.77
https://github.com/microsoft/pyright/blob/master/docs/typed-libraries.md

Could maybe remove the type stubs entirely:
https://devblogs.microsoft.com/python/pylance-introduces-five-new-features-that-enable-type-magic-for-python-developers/#5-py-typed-files-are-now-respected-when-using-the-uselibrarycodefortypes-setting

**Comment by christopherhesse** [comment]
https://github.com/microsoft/pyright/issues/1128

**Comment by christopherhesse** [comment]
https://youtrack.jetbrains.com/issue/PY-43203?clearDraft=true&description=%0A%0APC-201.7846.77

**Comment by christopher-hesse** [comment]
`pyright` now seems to support using libraries with inline type annotations (https://github.com/microsoft/pyright/commit/8cb9bfca41cb05ded74dde172472a2cfa6f42bd6).
