### ISSUE TITLE
Support for AWS S3

### ISSUE THREAD

**Issue by 8enmann** [christopher-hesse/blobfile#144]
I'm planning to start working on this today, let me know if there are any gotchas to consider

**Comment by christopher-hesse** [comment]
None that I am aware of.  I've been trying to avoid a dependency on boto though, so implementing the auth could be a pain.

**Comment by christopher-hesse** [comment]
I would guess the most annoying part is that ops.py is a large monolithic file.  There's `_azure.py` and `_google.py` but these specifically do not perform any requests.  If you want to avoid any refactoring, I'd guess there would be an `_amazon.py` that contains requestless code for amazon, and then just put the rest in `_ops.py`, trying to stick to the current naming scheme to make it easy to factor out later.

**Comment by christopher-hesse** [comment]
I partially refactored ops.py.  The eventual goal was to have a backend implement the following methods:

```
StreamingReadFile(ctx, path: str)
StreamingWriteFile(ctx, path: str)
maybe_stat(ctx, path: str) -> Optional[Stat]
remove(ctx, path: str) -> bool
maybe_update_md5(ctx, path: str, generation: str, hexdigest: str) -> bool
list_blobs(ctx, path: str, delimiter: Optional[str] = None) -> Iterator[DirEntry]
get_url(ctx, path: str) -> Tuple[str, Optional[float]]
join_paths(ctx, a: str, b: str) -> str
isdir(ctx, path: str) -> bool
mkdirfile(ctx, path: str) -> None
set_mtime(ctx, path: str, mtime: float, version: Optional[str] = None) -> bool
split_root(ctx, path: str) -> Tuple[str, str] (used in glob and rmdir and basename)
dirname(ctx, path: str) -> str
parallel_upload(executor: concurrent.futures.Executor, src: str, dst: str, return_md5: bool) -> Optional[str]
remote_copy(src: str, dst: str, overwrite: bool, return_md5: bool) -> Optional[str]
```

And then select the backend based on the path.  This is partially complete, but I won't have time to finish it right now.  If you don't want to finish the refactoring, you can just make this new backend match the existing code (maybe start by copying and pasting `_gcp.py`).

**Comment by 8enmann** [comment]
Finished stubbing everything out https://github.com/8enmann/blobfile/tree/aws
Starting impl now

**Comment by christopher-hesse** [comment]
I believe this was dropped due to the complexity of using AWS auth without a bunch of libraries.  Thanks anyway @8enmann!
