### ISSUE TITLE
Configurable test buckets

### ISSUE THREAD

**Issue by 8enmann** [christopher-hesse/blobfile#145]
https://github.com/christopher-hesse/blobfile/blob/bb885e72e97ddade675d4493db235b43888a2191/blobfile/_ops_test.py#L30-L36 make it hard for others to contribute, even if they have their own accounts

**Comment by christopher-hesse** [comment]
These could be environment variables to make them easily configurable.  The bigger issue is that the tests are not run via github actions (and in fact are only run on my desktop computer with the auth setup there).  Having them work with github actions would really make it a lot easier for people to contribute.

**Comment by christopher-hesse** [comment]
Also, just so you know I only run these tests inside of docker using https://github.com/christopher-hesse/blobfile/blob/master/testing/Dockerfile and I doubt they would work outside of that docker container.

**Comment by 8enmann** [comment]
This is now mostly solved in https://github.com/8enmann/blobfile/tree/aws
I added a gitignore'd .env file that I `source` before running tests. Probably need to add a reference to it somewhere in the test runner so docker picks up the overrides.

**Comment by 8enmann** [comment]
Fixed by #149

**Comment by christopher-hesse** [comment]
Oh geez now I’m getting emails from Microsoft about how I never answer
their calls.
