### ISSUE TITLE
Add ability to create contexts

### ISSUE THREAD

**Issue by christopher-hesse** [christopher-hesse/blobfile#147]
* [x] Rename `Context` to `Config` (and `ctx` to just `c`)
* [x] Create a `Context` object that has the `blobfile` public API on it (e.g. `listdir`, `md5`, etc) that takes a `Config` object on creation and stores it as a private instance variable
* [x] Add `create_context()` which takes the same arguments as `configure()`, creates a `Config` object and gives it to a new `Context` object, then returns the `Context` to the user (also export this object from `__init__.py`)
* [x] `configure()` should then call `create_context()` and set the global `_context` object (the global _context object will be set via `create_context()` on initialization)
* [x] The global functions such as `listdir()` etc will just call `_context.<method_name>()`
* [x] Update docs

Unfortunately, this implies that keyword arguments (and defaults) will be duplicated between `configure()` and `create_context()` as well as between the global functions and the methods on `Context`.

This is to enable more complicated configurations like @hauntsaninja was using where you don't want to fight with a script that calls `configure()`.

**Comment by christopherhesse** [comment]
Also allow overriding of `get_http_pool`

**Comment by christopherhesse** [comment]
Also, not clear if https://github.com/christopher-hesse/blobfile/blob/master/blobfile/_common.py#L331 works with lambda log_callback functions, or if it will work with overriding `get_http_pool`.
