### ISSUE TITLE
Add black check

### ISSUE THREAD

**Issue by 8enmann** [christopher-hesse/blobfile#151]
https://github.com/marketplace/actions/python-black-check

**Comment by christopher-hesse** [comment]
Ideally it might run testing/run.py which should always use the correct
version of black and also pyright

**Comment by 8enmann** [comment]
i'm a little wary of the deps necessary to get their test runners doing that, so going to start with the dumbest thing first

**Comment by 8enmann** [comment]
even pyright requires npm to install

**Comment by 8enmann** [comment]
oh looks like you can use a dockerfile, nvm
