### ISSUE TITLE
Any plan to support ADL?

### ISSUE THREAD

**Issue by JiushengChen** [christopher-hesse/blobfile#158]
Some pointers:
https://github.com/Azure/azure-data-lake-store-python
https://docs.microsoft.com/en-us/azure/data-lake-store/data-lake-store-comparison-with-blob-storage

**Comment by christopher-hesse** [comment]
Nah, it's blobfile not lakefile.  Plus https://github.com/Azure/azure-data-lake-store-python already has the operations you want to do I think.
