### ISSUE TITLE
better performance for readall() with streaming_read=False

### ISSUE THREAD

**Issue by christopherhesse** [christopher-hesse/blobfile#171]
`readall()` uses a 1MB buffer size, but with `streaming_read=False`, this is also the size of the request being made, so this should be a configurable setting and have a higher default.

Also make streaming_read=False the default.

**Comment by christopherhesse** [comment]
As @hauntsaninja suggested, this could also use a pre-allocated buffer instead of "".join

**Comment by christopher-hesse** [comment]
The preallocated buffer didn't seem to offer any speed advantage I was able to measure.
