### ISSUE TITLE
Expected behavior for blobfile.dirname("gs://a")

### ISSUE THREAD

**Issue by tomconerlyanth** [christopher-hesse/blobfile#203]
In this test `https://github.com/christopher-hesse/blobfile/blob/master/blobfile/_ops_test.py#L217` it checks that `blobfile.dirname("gs://a") == "gs://a"`. It seems more natural for dirname to be `"gs:"`. Is this a bug or expected behavior?

**Comment by christopher-hesse** [comment]
I guess that depends on if you think of the root directory as either `gs://a` or `gs:`, it looks like the rule blobfile uses is that `bf.dirname(path)` should not produce an invalid path and `gs:` is an invalid path (blobfile cannot do anything with that path).  I could see a case for either one, but probably wouldn't change it without a configuration flag to opt-in to the new behavior.
