### ISSUE TITLE
Remove hard vesion requirements for build time dependencies.

### ISSUE THREAD

**Issue by dreirund** [christopher-hesse/blobfile#206]
`pyproject.toml` requires very specific versions of build dependencies, but I could build it ([&nearr;&hairsp;Arch Linux package](https://aur.archlinux.org/packages/python-blobfile-git)) also with newer versions of the required modules (installed as operating system packages system-wide) after removing the ` == <version>`-statements.

So I suggest removing the strinct version requirements (maybe add ` >= <version>`, if a minimal version is required).

Regards!

**Comment by christopherhesse** [comment]
Thanks for the info!  Why does it matter what the build requirements are, aren't those only needed for the build?  Are multiple packages being built in the same environment?

**Comment by dreirund** [comment]
> Thanks for the info! Why does it matter what the build requirements are, aren't those only needed for the build?

Because operating system distribution might have different/ more up to date packages of the build dependencies, so installing a specific version might not be possible or breaking a lot of other packages? (Dependencies and build dependencies are installed as distribution packages, for clean installation.)

And, some packages might be not only build dependencies but also runtime dependencies (python modules which the software loads).
