### ISSUE TITLE
finish azure backend and update docs

### ISSUE THREAD

**Issue by christopher-hesse** [christopher-hesse/blobfile#32]
* [x] test azure backend with some production workloads
* [x] update docs to include information about azure backend

**Comment by christopherhesse** [comment]
https://docs.microsoft.com/en-us/cli/azure/storage?view=azure-cli-latest#az-storage-copy

`az storage copy` supports urls like `https://[account].blob.core.windows.net/[container]/[path/to/directory]`

**Comment by cshesse** [comment]
The azure backend will retry on an account that does not exist, it's hard to differentiate a transient network error from an invalid account.

**Comment by cshesse** [comment]
The invalid account stuff works now, just need testing + docs
