### ISSUE TITLE
Local cache for composite GCS objects

### ISSUE THREAD

**Issue by samsamoa** [christopher-hesse/blobfile#47]
BlobFile uses md5 hashes to handle local hashing.

`gsutil` uses composite objects to speed up uploads of large files. They do not have md5 hashes:
https://cloud.google.com/storage/docs/composite-objects
>  Composite objects do not have an MD5 hash metadata field.

`bf.md5` will fail when passed such a file:
```
  File "/usr/local/miniconda3/envs/openai/lib/python3.7/site-packages/blobfile/ops.py", line 1602, in md5
    return base64.b64decode(metadata["md5Hash"]).hex()
KeyError: 'md5Hash'
```

An option would be to use CRC32, which is available for these files.

**Comment by christopher-hesse** [comment]
It looks like this affects `md5` and `BlobFile` with `cache_dir` set.  Does it sound fine to you if `md5` returns `None` and `BlobFile` will use something like the hash of `(filepath, crc32)` for caching GCS files?

**Comment by samsamoa** [comment]
That sounds good to me! But you should enjoy your vacation, I wasn't expecting you to respond to this anytime soon :)
