### ISSUE TITLE
consider automatically making directories if they don't exist

### ISSUE THREAD

**Issue by christopherhesse** [christopher-hesse/blobfile#48]
When creating a local file, intermediate directories are not created automatically.  This operates a bit differently on GCS, where intermediate directories are created implicitly when the file is created.

The main downside to changing this is that people could be surprised when local directories are created automatically (for instance, they have a typo in the directory name).  It's unclear if that's worth worrying about though since they would have this problem on GCS anyway.

This amounts to doing `bf.makedirs(bf.dirname(path))` when creating a `BlobFile` in write mode.

One downside is that opening a write mode remote file will do an extra network request.

**Comment by daniel-ziegler** [comment]
You could decide to only do the `makedirs` if it indeed is a local file, saving the extra network request
