### ISSUE TITLE
Configurable connection pool size

### ISSUE THREAD

**Issue by christopherhesse** [christopher-hesse/blobfile#50]
Might improve efficiency in multi-threaded situations

* https://github.com/christopher-hesse/blobfile/blob/master/blobfile/ops.py#L143
* https://github.com/urllib3/urllib3/blob/master/src/urllib3/poolmanager.py#L441
* https://github.com/urllib3/urllib3/blob/29b214a129883301f91ae4a74fd7ef2958cbf7b0/src/urllib3/connectionpool.py#L135

**Comment by christopher-hesse** [comment]
May want to add `blobfile.configure(http_pool_max_size=10, log_callback=log_callback)`
