### ISSUE TITLE
Significant performance regression in 0.16.2

### ISSUE THREAD

**Issue by jpambrun** [christopher-hesse/blobfile#54]
Using the following code, going from 0.16.1 to 0.16.2 the performance goes from 230+ files per second to about 5. I can only assume this is the [offending commit](https://github.com/christopher-hesse/blobfile/commit/4b929353be1220844e9a4309555904b29cc7a25b).

``` python
import blobfile as bf
from tqdm import tqdm
from queue import Queue
from threading import Thread

pending_queue = Queue()
done_queue = Queue()

def downloadEnclosures(in_queue, out_queue):
    while True:
        filename = in_queue.get()
        with bf.BlobFile(filename, "rb") as f:
            content = f.read()
            out_queue.put(content)
        in_queue.task_done()

for i in range(64):
    worker = Thread(target=downloadEnclosures, args=(pending_queue,done_queue))
    worker.setDaemon(True)
    worker.start()

filename = 'gs:/path/to/a/200kb.file'
for i in range(10000):
    pending_queue.put(filename)

for i in tqdm(range(10000)):
  done_queue.get()

```

**Comment by jpambrun** [comment]
I guess it could also be [this commit](https://github.com/christopher-hesse/blobfile/commit/d9f1e3e9b595b0a80e45859136eef5ad6ab7286f) depending on when you change the version string.

**Comment by jpambrun** [comment]
I managed to fix it in 0.16.2 with `min(READALL_CHUNK_SIZE, self._size)` [here](https://github.com/christopher-hesse/blobfile/blob/master/blobfile/ops.py#L1769). With this 0.16.2 can go up to 250 files per sec again.

However, there is another regression between 0.16.2 and 0.16.6 since the same fix on 0.16.6 can only bring it up to about 30 files per sec.

**Comment by christopher-hesse** [comment]
Good catch!  I'm surprised that the performance differs so much, I will investigate.

**Comment by christopher-hesse** [comment]
I reduced the default size based on some performance tests, can you see if this solves your problem? https://github.com/christopher-hesse/blobfile/commit/34ef163b5e766272f5f10012e5aa849d2e150c43

**Comment by jpambrun** [comment]
For what it's worth, I began using geventhttpclient and it's best performance I could get with python so far. From google storage, I can download 10,000 200kb files in 15 second on one cpu core. That's about 1.2 gbps.

**Comment by christopher-hesse** [comment]
Okay, I'll assume this is fixed then.  I've gotten close to 30 gbps I think with blobfile and multiprocessing.

**Comment by jpambrun** [comment]
30 gbps with many small files or with few large files?

I am struggling with the many small file (~200kb) case. I could not really
get above 500-600 mbps with blobfile with multithreading and it was eating
all 4 cores. Tweaking max_conn didn't help either. Should I expect better
performance with small files?

**Comment by christopher-hesse** [comment]
I updated the comment, but I believe it was large files with
multiprocessing and many more cores.  Probably not applicable to your use
case.  An event loop approach sounds better for many small files.

Also it was awhile ago, so I don’t recall the exact details.

**Comment by christopher-hesse** [comment]
Yeah, it looks like 26 gbps with large files and a lot of cores.  For a large number of small files, gevent or asyncio sound like a better idea than threads, but blobfile doesn't use those so you're probably better off using those directly or switching that part of the code to go.

If you're using a GCE instance, you're also limited in network speed by the number of cores you have: https://cloud.google.com/compute/docs/machine-types#n1_standard_machine_types (it says egress, but I assume ingress is limited too)

**Comment by christopher-hesse** [comment]
Or assembling multiple small files into large files of course.

**Comment by jpambrun** [comment]
I know about the bandwidth limitations per core in GCE. I am currently using tfrecords to bundle small files into larger ones, but it's less flexible and I wanted to move away from that. 

Anyways, I am happy using gevent directly. I just wanted to share my results to let you know that, although this bug is fixed, there is still room for improvements with small files.

**Comment by christopher-hesse** [comment]
Thanks for reminding me about gevent!  I added a gevent example: https://github.com/christopher-hesse/blobfile#parallel-execution-with-gevent
