### ISSUE TITLE
colab notebook failure

### ISSUE THREAD

**Issue by christopherhesse** [christopher-hesse/blobfile#63]
`error (<urllib3.connection.HTTPConnection object at 0x7f92a12867b8>, 'Connection to metadata.google.internal timed out. (connect timeout=10)') when executing http request <blobfile.common.Request object at 0x7f92a1286898>, sleeping 0.8 seconds`

**Comment by christopher-hesse** [comment]
Looks like colab uses `NO_GCE_CHECK=True`
