### ISSUE TITLE
"host does not exist"

### ISSUE THREAD

**Issue by christopherhesse** [christopher-hesse/blobfile#79]
This can happen even if the host does exist.  The account detection code may need to be more robust.

**Comment by christopherhesse** [comment]
`_azure_get_access_token` could have a special retry loop where we verify that the account can be accessed before starting to use the token.  A prolonged network failure there would still cause a crash though.

The main `_execute_request` could then assume that any connection errors are transient.

**Comment by christopherhesse** [comment]
Alternatively, we can just check with a known-good DNS server instead: https://github.com/ValeryTyumen/DNS-Client

**Comment by christopher-hesse** [comment]
alternative method via checking the DNS server directly: https://gist.github.com/christopher-hesse/454e7ee0d7aa188e7d45af31a2a3314e

**Comment by christopher-hesse** [comment]
Should be fixed now in master, the DNS solution does not seem necessary to fix this on linux
