### ISSUE TITLE
fallback to storage keys

### ISSUE THREAD

**Issue by christopherhesse** [christopher-hesse/blobfile#81]
Service accounts should require a `AZURE_SUBSCRIPTION_ID` env var, so that we can fall back to reading storage account keys.

Also seems that keys should be the first thing to try and we should fallback to a normal oauth token, because there's no obvious way to guarantee that an oauth token will let us access a storage account.

**Comment by christopherhesse** [comment]
Unclear if this is actually necessary, since service accounts should just be given actual permissions.

**Comment by christopher-hesse** [comment]
Going to close this for now since it seems more like bad permissions than something that should actually be supported.
