### ISSUE TITLE
pyi files seem to disagree with pycharm for some reason

### ISSUE THREAD

**Issue by christopherhesse** [christopher-hesse/blobfile#97]

**Comment by christopherhesse** [comment]
Deleting `__init__.pyi` seems to fix the issue.

**Comment by christopher-hesse** [comment]
https://youtrack.jetbrains.com/issue/PY-43203?clearDraft=true&description=%0A%0APC-201.7846.77,%20JRE%2011.0.7%2B10-b765.53x64%20JetBrains%20s.r.o.,%20OS%20Windows%2010(amd64)%20v10.0%20,%20screens%203072x1728
